# frozen_string_literal: true

source "https://rubygems.org"

gem 'roda', '~> 3.46.0'
gem 'rack', '~> 2.2.0'
gem 'sequel', '~> 5.37.0'
gem 'sequel-paranoid', '~> 0.7.0'
gem 'sqlite3', '~> 1.4.0'
gem 'rack-cors', '~> 1.1.1'
gem 'puma', '~> 5.2.0'
gem 'roda-enhanced_logger', '~> 0.4.0'
gem 'tilt', '~>2.0.10'
gem 'erubi', '~>1.10.0'
gem 'bcrypt', '~> 3.1.15'
gem 'sequel_secure_password', '~> 0.2.0'
gem 'rack-attack', '~> 6.5.0'
gem 'auto_reloader', '~> 0.4.0'


group :development do
	gem 'faker', '~> 2.18.0'
end

group :test do
	gem 'rack-test', '~> 1.1.0'
end